import api from './api';
import { getCache, setCache } from '../database/repositories/cacheRepository';
import { farmStorage } from '../storage/farmStorage';
import { getIsConnected } from '../utils/networkStatus';
import {
  getReproductionEvents,
  createReproductionEvent as createLocalEvent,
  updateReproductionEvent as updateLocalEvent,
  deleteReproductionEvent as deleteLocalEvent,
  CreateReproductionEventData,
} from '../database/repositories/reproductionRepository';
import { getLocalAnimals } from '../database/repositories/animalRepository';
import { getLocalTypeEvenements } from '../database/repositories/typeEvenementRepository';
import {
  CreateReproductionEventRequest,
  ReproductionEvent,
  ReproductionEventType,
  ReproductionEventsResponse,
  ReproductionHistoriqueAnimalResponse,
} from '../types/reproduction.types';

const reproductionService = {
  async getEventTypes(): Promise<ReproductionEventType[]> {
    const farm = await farmStorage.getActiveFarm();
    const cacheKey = `event_types_${farm?.id || 'global'}`;

    // Try local database first
    try {
      const localTypes = await getLocalTypeEvenements();
      const reproductionTypes = localTypes.filter(t => t.categorie === 'REPRODUCTION');
      if (reproductionTypes.length > 0) {
        console.log('[ReproductionService] Event types from local database');
        return reproductionTypes;
      }
    } catch (localError) {
      console.error('[ReproductionService] Local read failed:', localError);
    }

    // Fallback to cache
    try {
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Event types from cache');
        return cached.payload;
      }
    } catch (cacheError) {
      console.warn('[ReproductionService] Cache read failed:', cacheError);
    }

    // Fallback to network
    try {
      const response = await api.get('/type-evenements');
      const data = response.data?.data || [];

      // Cache the result
      if (farm?.id) {
        await setCache(cacheKey, farm.id, data);
      }

      return data;
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching event types:', error);
      throw error;
    }
  },

  async getFemales(farmId?: string): Promise<any[]> {
    const farm = farmId ? { id: farmId } : await farmStorage.getActiveFarm();
    if (!farm) {
      throw new Error('No farm available');
    }

    const cacheKey = `females_${farm.id}`;

    // Try local database first
    try {
      const localAnimals = await getLocalAnimals(farm.id);
      const females = localAnimals.filter(a => a.sexe === 'femelle' && a.statut === 'ACTIF');
      if (females.length > 0) {
        console.log('[ReproductionService] Females from local database:', females.length);
        return females;
      }
    } catch (localError) {
      console.error('[ReproductionService] Local read failed:', localError);
    }

    // Fallback to cache
    try {
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Females from cache');
        return cached.payload;
      }
    } catch (cacheError) {
      console.warn('[ReproductionService] Cache read failed:', cacheError);
    }

    // Fallback to network
    try {
      console.log('[ReproductionService] Fetching females from network with farm_id:', farm.id);
      const response = await api.get('/animals', {
        params: { farm_id: farm.id, sexe: 'femelle', per_page: 100 },
      });
      const data = response.data?.data?.animals || [];
      console.log('[ReproductionService] Females from network:', data.length);

      // Cache the result
      await setCache(cacheKey, farm.id, data);

      return data;
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching females:', error);
      throw error;
    }
  },

  async createEvent(payload: CreateReproductionEventRequest): Promise<void> {
    const farm = await farmStorage.getActiveFarm();
    if (!farm) {
      throw new Error('No farm available');
    }

    const eventData: CreateReproductionEventData = {
      farm_id: farm.id,
      animal_id: payload.animal_id,
      type_evenement_id: payload.type_evenement_id,
      date_evenement: payload.date_evenement,
      description: payload.description,
      cout: payload.cout,
    };

    // Create in local database (adds to sync queue)
    // UUID will be auto-generated by reproductionRepository
    await createLocalEvent(eventData);

    console.log('[ReproductionService] Created reproduction event locally');
  },

  async getEvents(params?: Record<string, any>): Promise<ReproductionEventsResponse> {
    const farm = await farmStorage.getActiveFarm();
    if (!farm) {
      throw new Error('No farm available');
    }

    // Read from local database
    const events = await getReproductionEvents(farm.id);
    
    return { evenements: events };
  },

  async getEventById(id: string): Promise<ReproductionEvent> {
    // Try to get from local database first
    const farm = await farmStorage.getActiveFarm();
    if (farm) {
      const localEvent = await getReproductionEvents(farm.id);
      const found = localEvent.find(e => e.id === id);
      if (found) return found;
    }

    // Fallback to API if not found locally
    const response = await api.get(`/reproduction/evenements/${id}`);
    return response.data?.data;
  },

  async updateEvent(id: string, payload: Partial<CreateReproductionEventRequest> & { statut?: string }): Promise<ReproductionEvent> {
    // Use local repository for offline-first pattern
    await updateLocalEvent(id, payload);
    
    // Return the updated event from local database
    const farm = await farmStorage.getActiveFarm();
    if (farm) {
      const events = await getReproductionEvents(farm.id);
      const updated = events.find(e => e.id === id);
      if (updated) return updated;
    }
    
    throw new Error('Failed to retrieve updated event');
  },

  async deleteEvent(id: string): Promise<void> {
    // Use local repository for offline-first pattern
    await deleteLocalEvent(id);
  },

  async getReproductionDashboard(farmId: string): Promise<{ data: any; fromCache: boolean; cachedAt: string | null }> {
    const cacheKey = `reproduction_dashboard:${farmId}`;

    try {
      // Network request first
      const response = await api.get('/reproduction/dashboard', {
        params: { farm_id: farmId },
      });
      const data = response.data?.data || {};

      // Cache the result
      await setCache(cacheKey, farmId, data);

      return { data, fromCache: false, cachedAt: null };
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching dashboard:', error);
      // Fallback to cache on network error
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Dashboard from cache (fallback)');
        return { data: cached.payload, fromCache: true, cachedAt: cached.cachedAt };
      }
      throw error;
    }
  },

  async getForecast(farmId: string): Promise<{ data: any; fromCache: boolean; cachedAt: string | null }> {
    const cacheKey = `reproduction_forecast:${farmId}`;

    try {
      // Network request first
      const response = await api.get('/reproduction/forecast', {
        params: { farm_id: farmId },
      });
      const data = response.data?.data || {};

      // Cache the result
      await setCache(cacheKey, farmId, data);

      return { data, fromCache: false, cachedAt: null };
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching forecast:', error);
      // Fallback to cache on network error
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Forecast from cache (fallback)');
        return { data: cached.payload, fromCache: true, cachedAt: cached.cachedAt };
      }
      throw error;
    }
  },

  async getNaissancesPrevisions(farmId: string): Promise<{ data: any; fromCache: boolean; cachedAt: string | null }> {
    const cacheKey = `naissances_previsions:${farmId}`;

    try {
      // Network request first
      const response = await api.get('/reproduction/naissances/previsions', {
        params: { farm_id: farmId },
      });
      const data = response.data?.data || {};

      // Cache the result
      await setCache(cacheKey, farmId, data);

      return { data, fromCache: false, cachedAt: null };
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching naissances previsions:', error);
      // Fallback to cache on network error
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Naissances previsions from cache (fallback)');
        return { data: cached.payload, fromCache: true, cachedAt: cached.cachedAt };
      }
      throw error;
    }
  },

  async getAnimalHistorique(animalId: string): Promise<{ data: any; fromCache: boolean; cachedAt: string | null }> {
    const cacheKey = `reproduction_historique:${animalId}`;

    try {
      // Network request first
      const response = await api.get(`/reproduction/animals/${animalId}/historique`);
      const data = response.data?.data || {};

      // Cache the result
      const farm = await farmStorage.getActiveFarm();
      if (farm) {
        await setCache(cacheKey, farm.id, data);
      }

      return { data, fromCache: false, cachedAt: null };
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching animal historique:', error);
      // Fallback to cache on network error
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Animal historique from cache (fallback)');
        return { data: cached.payload, fromCache: true, cachedAt: cached.cachedAt };
      }
      throw error;
    }
  },

  async getAnimalStats(animalId: string): Promise<{ data: any; fromCache: boolean; cachedAt: string | null }> {
    const cacheKey = `reproduction_stats:${animalId}`;

    try {
      // Network request first
      const response = await api.get(`/reproduction/animals/${animalId}/stats`);
      const data = response.data?.data || {};

      // Cache the result
      const farm = await farmStorage.getActiveFarm();
      if (farm) {
        await setCache(cacheKey, farm.id, data);
      }

      return { data, fromCache: false, cachedAt: null };
    } catch (error: any) {
      console.error('[ReproductionService] Error fetching animal stats:', error);
      // Fallback to cache on network error
      const cached = await getCache(cacheKey);
      if (cached) {
        console.log('[ReproductionService] Animal stats from cache (fallback)');
        return { data: cached.payload, fromCache: true, cachedAt: cached.cachedAt };
      }
      throw error;
    }
  },
};

export default reproductionService;
