import { appSchema,tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 11,
  tables: [
    tableSchema({
      name: 'animals',
      columns: [
        { name: 'numero_identification', type: 'string' },
        { name: 'sexe', type: 'string' },
        { name: 'statut', type: 'string' },
        { name: 'date_naissance', type: 'string', isOptional: true },
        { name: 'poids', type: 'number', isOptional: true },
        { name: 'farm_id', type: 'string' },
        { name: 'espece_id', type: 'string' },
        { name: 'categorie_id', type: 'string', isOptional: true },
        { name: 'lot_id', type: 'string', isOptional: true },
        { name: 'mother_id', type: 'string', isOptional: true },
        { name: 'nom', type: 'string', isOptional: true },
        { name: 'race', type: 'string', isOptional: true },
        { name: 'photo', type: 'string', isOptional: true },
        { name: 'naissance_id', type: 'string', isOptional: true },
        { name: 'origine', type: 'string', isOptional: true },
        { name: 'etat_sante', type: 'string', isOptional: true },
        { name: 'farm_source_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isOptional: true },
        { name: 'version', type: 'number', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },

      ],
    }),
    tableSchema({
      name: 'evenements',
      columns: [
        { name: 'date_evenement', type: 'string' },
        { name: 'statut', type: 'string', isOptional: true },
        { name: 'date_fin', type: 'string', isOptional: true },
        { name: 'categorie', type: 'string' },
        { name: 'farm_id', type: 'string' },
        { name: 'animal_id', type: 'string', isOptional: true },
        { name: 'male_id', type: 'string', isOptional: true },
        { name: 'type_evenement_id', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'cout', type: 'number', isOptional: true },
        { name: 'farm_destination_id', type: 'string', isOptional: true },
        { name: 'statut_avant', type: 'string', isOptional: true },
        { name: 'statut_apres', type: 'string', isOptional: true },
        { name: 'transaction_id', type: 'string', isOptional: true },
        { name: 'metadonnees', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isOptional: true },
        { name: 'sync_error', type: 'string', isOptional: true },
        { name: 'last_push_attempt_at', type: 'number', isOptional: true },
        { name: 'server_confirmed_at', type: 'number', isOptional: true },
        { name: 'version', type: 'number', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'type_transaction', type: 'string' },
        { name: 'montant', type: 'number' },
        { name: 'date_transaction', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'farm_id', type: 'string' },
        { name: 'animal_id', type: 'string', isOptional: true },
        { name: 'evenement_id', type: 'string', isOptional: true },
        { name: 'categorie_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'tiers', type: 'string', isOptional: true },
        { name: 'numero_transaction', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isOptional: true },
        { name: 'sync_error', type: 'string', isOptional: true },
        { name: 'last_push_attempt_at', type: 'number', isOptional: true },
        { name: 'server_confirmed_at', type: 'number', isOptional: true },
        { name: 'version', type: 'number', isOptional: true },
        { name: 'last_modified_by', type: 'string' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'especes',
      columns: [
        { name: 'nom', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'nom_categorie', type: 'string' },
        { name: 'type', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'farm_id', type: 'string', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'type_evenements',
      columns: [
        { name: 'nom_type', type: 'string' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'categorie', type: 'string' },
        { name: 'farm_id', type: 'string', isOptional: true },
        { name: 'is_system', type: 'number' },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
   tableSchema({
      name: 'lots',
      columns: [
        { name: 'farm_id', type: 'string' },
        { name: 'nom_lot', type: 'string' },
        { name: 'nombre', type: 'number' },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'espece_id', type: 'string', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'farms',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'location', type: 'string', isOptional: true },
        { name: 'description', type: 'string', isOptional: true },
        { name: 'type_elevage', type: 'string', isOptional: true },
        { name: 'photo', type: 'string', isOptional: true },
        { name: 'owner_id', type: 'string', isOptional: true },
        { name: 'status', type: 'string', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'last_sync_at', type: 'number', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'naissances',
      columns: [
        { name: 'farm_id', type: 'string' },
        { name: 'mother_id', type: 'string' },
        { name: 'date_naissance', type: 'string' },
        { name: 'nombre_petits', type: 'number' },
        { name: 'poids_naissance', type: 'number', isOptional: true },
        { name: 'observation', type: 'string', isOptional: true },
        { name: 'evenement_id', type: 'string', isOptional: true },
        { name: 'date_saillie', type: 'string', isOptional: true },
        { name: 'date_mise_bas_prevue', type: 'string', isOptional: true },
        { name: 'pere_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isOptional: true },
        { name: 'sync_error', type: 'string', isOptional: true },
        { name: 'last_push_attempt_at', type: 'number', isOptional: true },
        { name: 'server_confirmed_at', type: 'number', isOptional: true },
        { name: 'version', type: 'number', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'notifications',
      columns: [
        { name: 'farm_id', type: 'string', isOptional: true },
        { name: 'animal_id', type: 'string', isOptional: true },
        { name: 'titre', type: 'string', isOptional: true },
        { name: 'message', type: 'string' },
        { name: 'sent_at', type: 'number', isOptional: true },
        { name: 'evenement_id', type: 'string', isOptional: true },
        { name: 'type', type: 'string' },
        { name: 'sync_status', type: 'string', isOptional: true },
        { name: 'sync_error', type: 'string', isOptional: true },
        { name: 'last_push_attempt_at', type: 'number', isOptional: true },
        { name: 'server_confirmed_at', type: 'number', isOptional: true },
        { name: 'version', type: 'number', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'farm_user',
      columns: [
        { name: 'farm_id', type: 'string' },
        { name: 'user_id', type: 'string' },
        { name: 'role', type: 'string', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'sante_rappels',
      columns: [
        { name: 'farm_id', type: 'string' },
        { name: 'animal_id', type: 'string' },
        { name: 'type_rappel', type: 'string' },
        { name: 'date_prevue', type: 'string' },
        { name: 'date_realisee', type: 'string', isOptional: true },
        { name: 'statut', type: 'string' },
        { name: 'note', type: 'string', isOptional: true },
        { name: 'evenement_id', type: 'string', isOptional: true },
        { name: 'sync_status', type: 'string', isOptional: true },
        { name: 'last_modified_by', type: 'string', isOptional: true },
        { name: 'version', type: 'number' },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
        { name: 'deleted_at', type: 'number', isOptional: true },
      ],
    }),
    tableSchema({
      name: 'sync_logs',
      columns: [
        { name: 'farm_id', type: 'string' },
        { name: 'table_name', type: 'string' },
        { name: 'record_id', type: 'string', isOptional: true },
        { name: 'sync_type', type: 'string' },
        { name: 'status', type: 'string' },
        { name: 'error_message', type: 'string', isOptional: true },
        { name: 'payload', type: 'string', isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
  ],
});
